language: minimal
dist: xenial
install:
    - sudo snap install hugo
before_install:
    - export TZ='Asia/Shanghai'
    - chmod +x ./publish.sh
after_script:
    - ./publish.sh
script:
    - hugo
branches:
    only:
        - hugo
env:
    global:
        # Github Pages
        - GH_REF: github.com/PhotonQuantum/PhotonQuantum.github.io.git
        # Coding Pages
        - CO_REF: git.dev.tencent.com/PhotonQuantum/lightquantum.xyz.git
