
favicon: favicon.ico
## 页面背景
page_background: /images/bg.jpg

## 页面菜单按钮风格
page_menu_button: dark

## 文章背景
post_background: /images/bg_post.jpg

## 文章菜单按钮风格
post_menu_button: light

## 标题占位字：无标题类型文章的标题占位字
title_plancehold: '随笔'

author:
  head: /avatar.png
  signature: 一颗正在寻求解脱的迷茫心灵

## 自定义菜单
navication:
  - name: 独角兽的梦
    link: https://qwq.cool

social:
  - name: GitHub
    icon: github
    link: https://github.com/PhotonQuantum
  - name: Zhihu
    icon: zhihu
    link: https://www.zhihu.com/people/chen-yan-zhu-85/
  - name: Bilibili
    icon: bilibili
    link: http://space.bilibili.com/28934599

duoshuo:
  enable: false
  siteName: ueibo

copyright:
  record: false
  hexo: true
  laughing: true

content_width: 1000
