version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    environment:
      GH_REF: github.com/PhotonQuantum/PhotonQuantum.github.io.git
      CO_REF: git.dev.tencent.com/PhotonQuantum/lightquantum.xyz.git
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init --recursive

      # build with Hugo
      - run: HUGO_ENV=production hugo --minify

      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy 
      - deploy:
          name: deploy to master
          command: bash publish.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: hugo
